apiVersion: v1
kind: Service
metadata:
  name: bravo-backend
  namespace: bravo
spec:
  type: ClusterIP
  selector:
    app: bravo-backend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
